" coding preferences
filetype off
filetype plugin indent on

syntax on
set backspace=indent,eol,start
set noautoindent
set noswapfile
set number
set ruler
set showmatch
set smarttab
set ts=2 sw=2 sts=2 expandtab

let mapleader=","
if has("autocmd")
  autocmd FileType go set ts=2 sw=2 sts=2 noet nolist autowrite
endif
